### ISSUE TITLE
Unexpected database error on startup

### ISSUE THREAD

**Issue by txuyuan** [AKEevee/Monster_Melancholy_v2.0.0#3]
Output of program: [log.txt](https://github.com/AKEevee/Monster_Melancholy_v2.0.0/files/7775397/log.txt)

Relevant info:
Wine v6.23
OS: Manjaro Linux
Kernel: 5.15.7

**Comment by AKEevee** [comment]
That should be because I left the uri string empty, you should fill it in with your own mongodb uri connection string :)
